M48
; DRILL file {KiCad 9.0.0-rc3} date 2025-02-21T17:01:55-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-21T17:01:55-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0-rc3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
%
G90
G05
T1
X4.5882Y-4.3709
X4.5882Y-4.4709
X6.475Y-3.5875
X6.475Y-3.6875
M30
